apiVersion: v1
kind: ConfigMap
metadata:
    name: gatekeeper-config
namespace: kc
data:
    keycloak-gatekeeper.conf: |+
        discovery-url: https://kc1.ktektest.us/auth/realms/kaylatek-test
        skip-openid-provider-tls-verify: true
        client-id: kubernetes
        client-secret: 999f606a-366a-4e05-a227-85dd04861351
        listen: :31014
        enable-refresh-tokens: true
        tls-cert: 
        tls-private-key:
        redirection-url: http://nginx.192.168.164.130.nip.io <need to find correct address>
        secure-cookie: false
        encryption-key: vGcLt8ZUdPX5fXhtLZaPHZkGWHZrT6aa <unsure what this should be>
        upstream-url: http://10.13.3.74:31014/ <need to find correct address>
        forbidden-page: /html/access-forbidden.html <need to create this in ingress?>
    resources:
    - uri: /*
      groups:
      - kubectl-cli-users
      - kubectl-cli-admin