kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: auth-test
  name: kubectl-cli-admin
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "pods", "services"]
  verbs: ["*"]